"""
Serverless API: Get incidents with filtering
Vercel Python Runtime
"""
from http.server import BaseHTTPRequestHandler
import json
from urllib.parse import urlparse, parse_qs
from pathlib import Path

# Load data from JSON file (generated by GitHub Actions scraper)
DATA_FILE = Path(__file__).parent.parent / "data" / "incidents.json"

def load_incidents():
      """Load incidents from JSON file"""
      if DATA_FILE.exists():
                with open(DATA_FILE, 'r') as f:
                              return json.load(f)
                      return []

  class handler(BaseHTTPRequestHandler):
        def do_GET(self):
                  # Parse query parameters
                  parsed = urlparse(self.path)
                  params = parse_qs(parsed.query)

            # Get filter values
                  country = params.get('country', [None])[0]
                  state = params.get('state', [None])[0]
                  city = params.get('city', [None])[0]
                  inc_type = params.get('type', [None])[0]
                  min_severity = params.get('min_severity', [None])[0]
                  limit = int(params.get('limit', [100])[0])
                  offset = int(params.get('offset', [0])[0])

            # Load and filter incidents
                  incidents = load_incidents()

            if country:
                incidents = [i for i in incidents if i.get('country') == country]
                      if state:
                          incidents = [i for i in incidents if i.get('state_province') == state]
                                if city:
                                    incidents = [i for i in incidents if i.get('city') == city]
                                          if inc_type:
                                              incidents = [i for i in incidents if i.get('incident_type') == inc_type]
                                                    if min_severity:
                                                        incidents = [i for i in incidents if (i.get('severity') or 0) >= int(min_severity)]

        # Sort by date descending
        incidents.sort(key=lambda x: x.get('incident_date') or '', reverse=True)

        # Paginate
        paginated = incidents[offset:offset + limit]

        # Send response
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.send_header('Access-Control-Allow-Origin', '*')
        self.end_headers()

        response = {
                      'incidents': paginated,
                      'count': len(paginated),
                      'total': len(incidents),
                      'limit': limit,
                      'offset': offset
        }

        self.wfile.write(json.dumps(response).encode())
